import { readFileSync, writeFileSync } from "node:fs";
import { copyFile, mkdir } from "node:fs/promises";

const ROOT_ENV = new URL("../../../.env", import.meta.url).pathname;
const PUBLIC_DOWNLOADS = new URL("../../../public/downloads/", import.meta.url)
	.pathname;
const DIST_DIR = new URL("../dist/", import.meta.url).pathname;

// Bun < 1.4.2 ships a darwin-arm64 compile runtime whose adhoc signature is
// rejected by macOS 26+/27 ("Killed: 9"). Pin the compiler so every target's
// outer signature is valid on current macOS.
const BUN_VERSION = "1.4.2";
const COMPILER = ["bunx", `bun@${BUN_VERSION}`];

type Target = {
	triple: string;
	os: string;
	outfile: string;
};

const TARGETS: Record<string, Target> = {
	win: {
		triple: "bun-windows-x64",
		os: "win",
		outfile: "ITSM-AssetCollector.exe",
	},
	mac: {
		triple: "bun-darwin-arm64",
		os: "mac",
		outfile: "itsm-asset-collector-macos-arm64",
	},
	linux: {
		triple: "bun-linux-x64",
		os: "linux",
		outfile: "itsm-asset-collector-linux-x64",
	},
};

function parseTargets(argv: string[]): Target[] {
	const requested: string[] = [];
	for (let i = 0; i < argv.length; i += 1) {
		if (argv[i] === "--os") {
			requested.push(...(argv[i + 1] ?? "").split(",").filter(Boolean));
			i += 1;
		} else if (argv[i].startsWith("--os=")) {
			requested.push(
				...argv[i].slice("--os=".length).split(",").filter(Boolean),
			);
		}
	}

	if (requested.length === 0 || requested.includes("all")) {
		return Object.values(TARGETS);
	}
	const unknown = requested.filter((name) => !(name in TARGETS));
	if (unknown.length > 0) {
		console.error(
			`Unknown target(s): ${unknown.join(", ")}. Valid: all, win, mac, linux.`,
		);
		process.exit(1);
	}
	return requested.map((name) => TARGETS[name]);
}

function readRootEnvUrl(): string {
	const raw = readFileSync(ROOT_ENV, "utf8");
	const match = /^APP_URL\s*=\s*(.+?)\s*$/m.exec(raw);
	const value = match?.[1] ?? "";
	return value.replace(/^["']|["']$/g, "");
}

const appUrl = readRootEnvUrl();
if (!appUrl) {
	console.error(
		"APP_URL is not set in .env at the repository root. Set it and re-run (or pass --url at runtime).",
	);
	process.exit(1);
}

const generated = `// This file is auto-generated by scripts/build.ts. Do not edit.

export const DEFAULT_APP_URL = ${JSON.stringify(appUrl)};
`;
writeFileSync(
	new URL("../src/build-config.ts", import.meta.url).pathname,
	generated,
);
console.log(`Injected APP_URL="${appUrl}" into src/build-config.ts`);

const targets = parseTargets(process.argv.slice(2));
for (const target of targets) {
	const args = [
		...COMPILER,
		"build",
		"--compile",
		`--target=${target.triple}`,
		"--outfile",
		`dist/${target.outfile}`,
		"src/index.ts",
	];

	console.log(`\n[${target.os}] bun@${BUN_VERSION} build --compile ...`);
	const proc = Bun.spawn(args, {
		stdout: "inherit",
		stderr: "inherit",
	});
	const exitCode = await proc.exited;
	if (exitCode !== 0) {
		process.exit(exitCode);
	}
	console.log(`Built dist/${target.outfile}`);

	await mkdir(PUBLIC_DOWNLOADS, { recursive: true });
	await copyFile(
		`${DIST_DIR}${target.outfile}`,
		`${PUBLIC_DOWNLOADS}${target.outfile}`,
	);
	console.log(`Copied to public/downloads/${target.outfile}`);
}
console.log("\nAll targets built.");
